all: run

laplace2d: laplace2d.c common.h laplace2d_serial.h Makefile
	pgcc -fast -acc -ta=nvidia laplace2d.c -o laplace2d

clean:
	rm -f laplace2d laplace2d.solution laplace2d.*.nvvp

run: laplace2d
	./laplace2d

profile: laplace2d
	nvprof -o laplace2d.nvvp ./laplace2d

laplace2d.solution: laplace2d.solution.c common.h laplace2d_serial.h Makefile
	pgcc -fast -acc -ta=nvidia laplace2d.solution.c -o laplace2d.solution

solution: laplace2d.solution
	./laplace2d.solution

